name: Build & Push API Image
on:
  push:
    branches: ["main"]
    paths:
      - "unified_field_v0/**"
      - ".github/workflows/build-and-push.yml"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push
        env:
          IMAGE: ghcr.io/cjo93/defrag
          SHA: ${{ github.sha }}
        run: |
          docker build -t "$IMAGE:latest" -t "$IMAGE:$SHA" -f unified_field_v0/Dockerfile .
          docker push "$IMAGE:latest"
          docker push "$IMAGE:$SHA"

      - name: Summary
        env:
          IMAGE: ghcr.io/cjo93/defrag
        run: echo "Pushed $IMAGE:latest" >> $GITHUB_STEP_SUMMARY
