name: Build & Push API Image
on:
  push:
    branches: ["main"]
    paths:
      - "unified_field_v0/**"
      - ".github/workflows/build-and-push.yml"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repo checkout
        uses: actions/checkout@v4

      - name: Print context
        run: |
          echo "Actor=${GITHUB_ACTOR}"
          echo "Repo=${GITHUB_REPOSITORY}"
          echo "Ref=${GITHUB_REF}"
          echo "SHA=${GITHUB_SHA}"

      - name: Docker info
        run: |
          docker info
          docker version

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push (ghcr.io/cjo93/defrag)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: unified_field_v0/Dockerfile
          push: true
          tags: |
            ghcr.io/cjo93/defrag:latest
            ghcr.io/cjo93/defrag:${{ github.sha }}
          provenance: false
          sbom: false
