name: Build & Push API Image
on:
  push:
    branches: ["main"]
    paths:
      - "unified_field_v0/**"
      - ".github/workflows/build-and-push.yml"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: ./unified_field_v0
          file: ./unified_field_v0/Dockerfile
          push: true
          tags: |
            ghcr.io/cjo93/defrag:latest
            ghcr.io/cjo93/defrag:${{ github.sha }}
          provenance: false
          sbom: false
